pub mod config;
pub mod debug;
pub mod eda;
pub mod edit_magic;
pub mod file_magics;
pub mod history_magics;
pub mod inspect;
#[cfg(feature = "tui")]
pub mod inspect_tui;
pub mod logging;
pub mod lsmagic;
pub mod magic_help;
pub mod r_utils;
pub mod shell;
pub mod timing;
pub mod workspace;
